name: RunFOSSAscan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fossa-scan:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run FOSSA scan
        id: fossa-scan
        env:
          FOSSA_API_KEY: ${{ secrets.FOSSA_API_KEY }}
        run: |
          curl -H 'Cache-Control: no-cache' https://raw.githubusercontent.com/fossas/fossa-cli/master/install-latest.sh | sudo bash
          fossa --version
          fossa analyze --x-vendetta
          fossa test
